Entity/Media/Album.php
<?php

namespace Maci\PageBundle\Entity\Media;

/**
 * Album
 */
class Album
{
	/**
	 * @var integer
	 */
	private $id;

	/**
	 * @var string
	 */
	private $name;

	/**
	 * @var string
	 */
	private $subtitle;

	/**
	 * @var string
	 */
	private $description;

	/**
	 * @var string
	 */
	private $meta_title;

	/**
	 * @var text
	 */
	private $meta_description;

	/**
	 * @var string
	 */
	private $type;

	/**
	 * @var string
	 */
	private $redirect;

	/**
	 * @var integer
	 */
	private $position;

	/**
	 * @var \Doctrine\Common\Collections\Collection
	 */
	private $children;

	/**
	 * @var \Maci\PageBundle\Entity\Media\Album
	 */
	private $parent;

	/**
	 * @var \Maci\PageBundle\Entity\Media\Media
	 */
	private $preview;

	/**
	 * @var \Doctrine\Common\Collections\Collection
	 */
	private $items;

	/**
	 * @var \Doctrine\Common\Collections\Collection
	 */
	protected $translations;

	/**
	 * @var string
	 */
	private $locale;

	/**
	 * Constructor
	 */
	public function __construct()
	{
		$this->children = new \Doctrine\Common\Collections\ArrayCollection();
		$this->items = new \Doctrine\Common\Collections\ArrayCollection();
		$this->translations = new \Doctrine\Common\Collections\ArrayCollection();
		$this->type = 'album';
	}

	/**
	 * Get id
	 *
	 * @return integer 
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Set name
	 *
	 * @param string $name
	 * @return Album
	 */
	public function setName($name)
	{
		$this->name = $name;
	
		return $this;
	}

	/**
	 * Get name
	 *
	 * @return string 
	 */
	public function getName()
	{
		return $this->name;
	}

	public function getLabel()
	{
		return (strlen($this->getName()) ? $this->getName() : 'Album[' . $this->getId() . ']');
	}

	public function setSubtitle($subtitle)
	{
		$this->subtitle = $subtitle;

		return $this;
	}

	public function getSubtitle()
	{
		return $this->subtitle;
	}

	/**
	 * Set description
	 *
	 * @param string $description
	 * @return Album
	 */
	public function setDescription($description)
	{
		$this->description = $description;
	
		return $this;
	}

	/**
	 * Get description
	 *
	 * @return string 
	 */
	public function getDescription()
	{
		return $this->description;
	}

	/**
	 * Set title
	 */
	public function setMetaTitle($meta_title)
	{
		$this->meta_title = $meta_title;

		return $this;
	}

	/**
	 * Get title
	 */
	public function getMetaTitle()
	{
		return $this->meta_title;
	}

	/**
	 * Set description
	 */
	public function setMetaDescription($meta_description)
	{
		$this->meta_description = $meta_description;

		return $this;
	}

	/**
	 * Get description
	 */
	public function getMetaDescription()
	{
		return $this->meta_description;
	}

	/**
	 * Set type
	 *
	 * @param string $type
	 * @return Album
	 */
	public function setType($type)
	{
		$this->type = $type;

		return $this;
	}

	/**
	 * Get type
	 *
	 * @return string 
	 */
	public function getType()
	{
		return $this->type;
	}

	public function getTypeArray()
	{
		return array(
			'Gallery' => 'gallery',
			'Products' => 'products',
			'Album' => 'album'
		);
	}

	public function getTypeLabel()
	{
		$array = $this->getTypeArray();
		if (array_key_exists($this->type, $array)) {
			return $array[$this->type];
		}
		$str = str_replace('_', ' ', $this->type);
		return ucwords($str);
	}

	/**
	 * Set redirect
	 *
	 * @param string $redirect
	 * @return string
	 */
	public function setRedirect($redirect)
	{
		$this->redirect = $redirect;

		return $this;
	}

	/**
	 * Get redirect
	 *
	 * @return string 
	 */
	public function getRedirect()
	{
		return $this->redirect;
	}

	/**
	 * Set position
	 *
	 * @param integer $position
	 * @return Album
	 */
	public function setPosition($position)
	{
		$this->position = $position;

		return $this;
	}

	/**
	 * Get position
	 *
	 * @return integer 
	 */
	public function getPosition()
	{
		return $this->position;
	}

	public function setLocale($locale)
	{
		$this->locale = $locale;

		return $this;
	}

	public function getLocale()
	{
		return $this->locale;
	}

	/**
	 * Add children
	 *
	 * @param \Maci\PageBundle\Entity\Media\Album $children
	 * @return Album
	 */
	public function addChild(\Maci\PageBundle\Entity\Media\Album $children)
	{
		$this->children[] = $children;

		return $this;
	}

	/**
	 * Remove children
	 *
	 * @param \Maci\PageBundle\Entity\Media\Album $children
	 */
	public function removeChild(\Maci\PageBundle\Entity\Media\Album $children)
	{
		$this->children->removeElement($children);
	}

	/**
	 * Get children
	 *
	 * @return \Doctrine\Common\Collections\Collection 
	 */
	public function getChildren()
	{
		return $this->children;
	}

	/**
	 * Set parent
	 *
	 * @param \Maci\PageBundle\Entity\Media\Album $parent
	 * @return Album
	 */
	public function setParent(\Maci\PageBundle\Entity\Media\Album $parent = null)
	{
		$this->parent = $parent;

		return $this;
	}

	/**
	 * Get parent
	 *
	 * @return \Maci\PageBundle\Entity\Media\Album 
	 */
	public function getParent()
	{
		return $this->parent;
	}

	public function getParentsList()
	{
		$list = array();
		$obj = $this->parent;
		while (is_object($obj)) {
			$list[] = $obj;
			$obj = $obj->getParent();
		}
		return array_reverse($list);
	}

	/**
	 * Set preview
	 *
	 * @param \Maci\PageBundle\Entity\Media\Media $preview
	 * @return Album
	 */
	public function setPreview(\Maci\PageBundle\Entity\Media\Media $preview = null)
	{
		$this->preview = $preview;

		return $this;
	}

	/**
	 * Get preview
	 *
	 * @return \Maci\PageBundle\Entity\Media\Media 
	 */
	public function getPreview()
	{
		return $this->preview;
	}

	public function getWebPreview()
	{
		if ($this->preview) {
			return $this->preview->getWebPreview();
		}
		return '/images/defaults/folder-icon.png';
	}

	/**
	 * Add items
	 *
	 * @param \Maci\PageBundle\Entity\Media\Item $items
	 * @return Album
	 */
	public function addItem(\Maci\PageBundle\Entity\Media\Item $items)
	{
		$this->items[] = $items;

		return $this;
	}

	/**
	 * Remove items
	 *
	 * @param \Maci\PageBundle\Entity\Media\Item $items
	 */
	public function removeItem(\Maci\PageBundle\Entity\Media\Item $items)
	{
		$this->items->removeElement($items);
	}

	/**
	 * Get items
	 *
	 * @return \Doctrine\Common\Collections\Collection 
	 */
	public function getItems()
	{
		return $this->items;
	}

	/**
	 * Get public media
	 *
	 * @return \Doctrine\Common\Collections\Collection 
	 */
	public function getPrivateMedia()
	{
		return $this->items->filter(function($e){
			return !$e->getMedia()->getPublic();
		});
	}

	/**
	 * Get media | Images
	 *
	 * @return \Doctrine\Common\Collections\Collection 
	 */
	public function getPrivateDocuments()
	{
		return $this->getPrivateMedia()->filter(function($e){
			return $e->getType() == 'document';
		});
	}

	/**
	 * Get public media
	 *
	 * @return \Doctrine\Common\Collections\Collection 
	 */
	public function getPublicMedia()
	{
		return $this->items->filter(function($e){
			return ( is_object($e->getMedia()) ? $e->getMedia()->getPublic() : false );
		});
	}

	/**
	 * Get media | Images
	 *
	 * @return \Doctrine\Common\Collections\Collection 
	 */
	public function getImages()
	{
		return $this->getPublicMedia()->filter(function($e){
			return $e->getMedia()->getType() == 'image';
		});
	}

	public function getSlides()
	{
		return $this->items->filter(function($e){
			return ( is_object($e->getMedia()) ? $e->getMedia()->getPublic() : true );
		});
	}

	/**
	 * 
	 */
	public function setUpdatedValue()
	{
		$this->updated = new \DateTime;
	}

	/**
	 * 
	 */
	public function setCreatedValue()
	{
		$this->created = new \DateTime;
	}

	/**
	 * __toString()
	 */
	public function __toString()
	{
		return $this->getLabel();
	}
}

Entity/Media/Item.php
<?php

namespace Maci\PageBundle\Entity\Media;

/**
 * Item
 */
class Item
{
	/**
	 * @var integer
	 */
	private $id;

	/**
	 * @var string
	 */
	private $title;

	/**
	 * @var string
	 */
	private $content;

	/**
	 * @var boolean
	 */
	private $favourite;

	/**
	 * @var string
	 */
	private $link;

	/**
	 * @var string
	 */
	private $style;

	/**
	 * @var string
	 */
	private $video;

	/**
	 * @var integer
	 */
	private $position;

	/**
	 * @var \Maci\PageBundle\Entity\Media\Album
	 */
	private $album;

	/**
	 * @var \Maci\PageBundle\Entity\Media\Tag
	 */
	private $brand;

	/**
	 * @var \Maci\PageBundle\Entity\Media\Album
	 */
	private $gallery;

	/**
	 * @var \Maci\PageBundle\Entity\Media\Media
	 */
	private $media;

	/**
	 * @var \Doctrine\Common\Collections\Collection
	 */
	protected $translations;

	/**
	 * Constructor
	 */
	public function __construct()
	{
		$this->favourite = false;
		$this->translations = new \Doctrine\Common\Collections\ArrayCollection();
		$this->style = 'default';
	}

	/**
	 * Get id
	 *
	 * @return integer 
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Set title
	 *
	 * @param string $title
	 * @return Item
	 */
	public function setTitle($title)
	{
		$this->title = $title;
	
		return $this;
	}

	/**
	 * Get title
	 *
	 * @return string 
	 */
	public function getTitle()
	{
		return $this->title;
	}

	/**
	 * Set content
	 *
	 * @param string $content
	 * @return Item
	 */
	public function setContent($content)
	{
		$this->content = $content;
	
		return $this;
	}

	/**
	 * Get content
	 *
	 * @return string 
	 */
	public function getContent()
	{
		return $this->content;
	}

	/**
	 * Get favourite.
	 *
	 * @return bool
	 */
	public function getFavourite()
	{
		return $this->favourite;
	}

	/**
	 * Set favourite
	 *
	 * @param boolean $favourite
	 * @return Item
	 */
	public function setFavourite($favourite)
	{
		$this->favourite = $favourite;

		return $this;
	}

	/**
	 * Get favourite
	 *
	 * @return boolean 
	 */
	public function isFavourite()
	{
		return $this->favourite;
	}

	public function setLink($link)
	{
		$this->link = $link;

		return $this;
	}

	public function getLink()
	{
		return $this->link;
	}

	/**
	 * Set style
	 *
	 * @param integer $style
	 * @return Item
	 */
	public function setStyle($style)
	{
		$this->style = $style;

		return $this;
	}

	/**
	 * Get style
	 *
	 * @return string 
	 */
	public function getStyle()
	{
		return $this->style;
	}

	static public function getStyleArray()
	{
		return [
			'Default' => 'default',
			'Image & Text - Center' => 'center',
			'Image & Text - Center Overlay' => 'center_ov',
			'Image & Text - Center Fix' => 'center_fix',
			'Image & Text - Center Fix Overlay' => 'center_fix_ov',
			'Image & Text - Left' => 'left',
			'Image & Text - Left Overlay' => 'left_ov',
			'Image & Text - Left Divided' => 'left_divided',
			'Image & Text - Right' => 'right',
			'Image & Text - Right Overlay' => 'right_ov',
			'Image & Text - Right Divided' => 'right_divided',
			'Text - Text Only' => 'text_only',
			'Text - Text Only Full' => 'text_only_full',
			'Blog - Last Posts' => 'last_posts',
			'Company' => 'company',
			'Contacts - Contact Info' => 'contact_info',
			'Contacts - Contact Form' => 'contact_form',
			'Contacts - Contact Form Overlay' => 'contact_form_ov',
			'Slider, only Indicators' => 'slider',
			'Slider Minimal' => 'slider_one',
			'Slider with Caption' => 'slider_two',
			'Locked Slider' => 'slider_three',
			'Gallery - Album Preview' => 'album_preview',
			'Gallery - Album' => 'album',
			'Gallery - Grid' => 'quads',
			'Gallery - Gallery 3IA' => 'gallery',
			'Gallery - Gallery 2IA' => 'gallery_a',
			'Gallery - Gallery 4IA' => 'gallery_b',
			'Gallery - Gallery 6IA' => 'gallery_c',
			'Gallery - Gallery 2IB' => 'gallery_d',
			'Gallery - Gallery 3IB' => 'gallery_e',
			'Gallery - Gallery 4IB' => 'gallery_f',
			'Gallery - Gallery 6IB' => 'gallery_g',
			'Gallery - Gallery 2CI' => 'gallery_h',
			'Gallery - Gallery 3CI' => 'gallery_i',
			'Gallery - Gallery 4CI' => 'gallery_j',
			'Gallery - Gallery 6CI' => 'gallery_k',
			'Gallery - Static Image' => 'static_image',
			'Other - One' => 'one',
			'Other - Two' => 'two',
			'Other - Three' => 'three',
			'Other - Foo' => 'foo'
		];
	}

	public function getStyleLabel()
	{
		$array = $this->getStyleArray();
		$key = array_search($this->style, $array);
		if ($key) {
			return $key;
		}
		$str = str_replace('_', ' ', $this->style);
		return ucwords($str);
	}

	public function setVideo($video)
	{
		$this->video = $video;

		return $this;
	}

	public function getVideo()
	{
		return $this->video;
	}

	/**
	 * Set position
	 *
	 * @param integer $position
	 * @return Item
	 */
	public function setPosition($position)
	{
		$this->position = $position;

		return $this;
	}

	/**
	 * Get position
	 *
	 * @return integer 
	 */
	public function getPosition()
	{
		return $this->position;
	}

	/**
	 * Set album
	 *
	 * @param \Maci\PageBundle\Entity\Media\Album $album
	 * @return Item
	 */
	public function setAlbum(\Maci\PageBundle\Entity\Media\Album $album = null)
	{
		$this->album = $album;

		return $this;
	}

	/**
	 * Get album
	 *
	 * @return \Maci\PageBundle\Entity\Media\Album 
	 */
	public function getAlbum()
	{
		return $this->album;
	}

	/**
	 * Set gallery
	 *
	 * @param \Maci\PageBundle\Entity\Media\Album $gallery
	 * @return Item
	 */
	public function setGallery(\Maci\PageBundle\Entity\Media\Album $gallery = null)
	{
		$this->gallery = $gallery;

		return $this;
	}

	/**
	 * Get gallery
	 *
	 * @return \Maci\PageBundle\Entity\Media\Album 
	 */
	public function getGallery()
	{
		return $this->gallery;
	}

	/**
	 * Set brand
	 *
	 * @param \Maci\PageBundle\Entity\Media\Tag $brand
	 * @return Item
	 */
	public function setBrand(\Maci\PageBundle\Entity\Media\Tag $brand = null)
	{
		$this->brand = $brand;

		return $this;
	}

	/**
	 * Get brand
	 *
	 * @return \Maci\PageBundle\Entity\Media\Tag 
	 */
	public function getBrand()
	{
		return $this->brand;
	}

	/**
	 * Set media
	 *
	 * @param \Maci\PageBundle\Entity\Media\Media $media
	 * @return Item
	 */
	public function setMedia(\Maci\PageBundle\Entity\Media\Media $media = null)
	{
		$this->media = $media;

		return $this;
	}

	/**
	 * Get media
	 *
	 * @return \Maci\PageBundle\Entity\Media\Media 
	 */
	public function getMedia()
	{
		return $this->media;
	}


	public function getWebPreview()
	{
		if ($this->media) {
			return $this->media->getWebPreview();
		}
		return '/images/defaults/no-icon.png';
	}


	public function getTags()
	{
		if ($this->media) {
			return $this->media->getTags();
		}
		return false;
	}

	/**
	 * __toString()
	 */
	public function __toString()
	{
		return (strlen($this->getTitle()) ? $this->getTitle() : 'MediaItem:' . ($this->getId() ? $this->getId() : 'new'));
	}
}

Controller/MediaController.php
<?php

namespace Maci\PageBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\BinaryFileResponse;

class MediaController extends AbstractController
{
	public function indexAction()
	{
		$list = $this->getDoctrine()->getManager()
			->getRepository('MaciPageBundle:Media\Media')
			->getList();

		return $this->render('MaciPageBundle:Media:index.html.twig', array('list' => $list));
	}

	public function tagAction($id)
	{
		$tag = $this->getDoctrine()->getManager()
			->getRepository('MaciPageBundle:Media\Tag')
			->findOneById($id);

		if (!$tag) {
			return $this->redirect($this->generateUrl('maci_media'));
		}

		return $this->render('MaciPageBundle:Media:tag.html.twig', array('tag' => $tag));
	}

	public function tagsAction($type)
	{
		$list = $this->getDoctrine()->getManager()
			->getRepository('MaciPageBundle:Media\Tag')
			->findBy(array(
				'type' => $type
			));

		return $this->render('MaciPageBundle:Media:tags.html.twig', array('list' => $list));
	}

	public function brandsAction()
	{
		$list = $this->getDoctrine()->getManager()
			->getRepository('MaciPageBundle:Media\Tag')
			->findBy(array(
				'type' => 'brand'
			));

		return $this->render('MaciPageBundle:Media:brands.html.twig', array('list' => $list));
	}

	public function galleryAction($type)
	{
		$item = new \Maci\PageBundle\Entity\Media\Album;
		if (!in_array($type, array_values($item->getTypeArray()))) {
			$type = 'gallery';
		}

		$list = $this->getDoctrine()->getManager()
			->getRepository('MaciPageBundle:Media\Album')
			->getGallery($type);

		return $this->render('MaciPageBundle:Media:gallery.html.twig', array('list' => $list));
	}

	public function albumAction($id)
	{
		$album = $this->getDoctrine()->getManager()
			->getRepository('MaciPageBundle:Media\Album')
			->findOneById($id);

		if (!$album) {
			return $this->redirect($this->generateUrl('maci_media'));
		}

		return $this->render('MaciPageBundle:Media:album.html.twig', array('album' => $album));
	}

	public function sliderAction($id)
	{
		$list = $this->getDoctrine()->getManager()
			->getRepository('MaciPageBundle:Media\Album')
			->getOneById($id);

		return $this->render('MaciPageBundle:Media:_slider.html.twig', array('album' => $album));
	}

	public function libraryAction()
	{
		$list = $this->getDoctrine()->getManager()
			->getRepository('MaciPageBundle:Media\Permission')
			->findBy(array(
				'user' => $this->getUser(),
				'status' => 'end'
			));

		return $this->render('MaciPageBundle:Media:library.html.twig', array('list' => $list));
	}

	public function getAction($path)
	{
		$media = $this->getDoctrine()->getManager()
			->getRepository('MaciPageBundle:Media\Media')
			->findOneByPath($path);

		if ($media) {
			if (!$media->getPublic()) {
				$permission = $this->getDoctrine()->getManager()
					->getRepository('MaciPageBundle:Media\Permission')
					->findOneBy(array(
						'user' => $this->getUser(),
						'media' => $media,
						'status' => 'end'
					));
				if ($permission) {
					return new BinaryFileResponse($media->getAbsolutePath());
				}
				return new Response();
			} else {
				return new BinaryFileResponse($media->getAbsolutePath());
			}
		}
		return new Response();
	}
}

Resources/views/Media/_album_item.html.twig
<div class="media-item row">

	<input name="id" type="hidden" value="{{ item.id }}" />

	<div class="media-preview">
	<a href="{{ path('maci_media_album', {'id': item.id}) }}">
		{% include "@MaciPage/Media/_media_preview.html.twig" with { 'item': item } %}
	</a>
	</div>

	<div class="media-info">

	<a href="{{ path('maci_media_album', {'id': item.id}) }}">
		<h4 class="media-title">{{ item }}</h4>
	</a>

	</div>

</div>

Resources/views/Media/_album_list.html.twig
{% if album is not defined %}
{% set album = false %}
{% endif %}


{% if list|length %}

<div class="container-fluid">

<div class="row">


{% for item in list %}


<div class="col-xs-12 col-sm-6 col-md-3 {% if loop.index is odd %}odd{% else %}even{% endif %}">

	{% include "@MaciPage/Media/_album_item.html.twig" with { 'item': item, 'album': album } %}

</div>


{% if ( loop.index % 2 ) == 0 and not ( loop.index % 4 ) == 0 %}

<div class="clearfix visible-sm-block"></div>

{% endif %}


{% if ( loop.index % 4 ) == 0 and not loop.last %}

</div><div class="row">

{% endif %}


{% endfor %}


</div>

</div>

{% endif %}

Resources/views/Media/_album_preview.html.twig
<section class="album preview">

<header class="album-header container-fluid">

	<a href="{{ path('maci_media_album', {'id': album.id}) }}">
		<h3 class="album-title">{{ album.name }}</h3>
	</a>
	<p class="lead">{{ album.description|raw }}</p>

</header>

{% if album.children|length %}
<section class="album-children">

	{% include "@MaciPage/Media/_album_list.html.twig" with { 'list': album.children } %}

</section>
{% endif %}

{% if album.subtitle %}
<section class="album-subtitle container-fluid">

	<h4 class="album-subtitle">{{ album.subtitle }}</h4>

</section>
{% endif %}

<section class="album-media">

	{% include "@MaciPage/Media/_album_media_list.html.twig" with { 'limit': 12 } %}

</section>

<footer class="album-see-more container-fluid">

	<a class="btn" href="{{ path('maci_media_album', {'id': album.id}) }}">
		{{ 'media.album.preview.see_more' | matra('See More') }}
		<span class="glyphicon glyphicon-chevron-right"></span>
	</a>

</footer>

</section>

Resources/views/Media/_media_preview.html.twig
<img class="img-fluid" src="{{ src is defined ? src : asset(item.webPreview | imagine_filter('maci_media_preview')) }}" {% if item.description %} title="{{ item.name }}" alt="{{ item.description }}" {% else %} alt="{{ item.name ? item.name : '#' }}" {% endif %} />

Resources/views/Media/_slider_multiple.html.twig
{% if slider_filter is not defined %}
{% set slider_filter = 'maci_media_gallery' %}
{% endif %}

{% if multiple_len is defined %}
{% if multiple_len == 2 %}
{% set multiple_class = 'col-xs-12 col-sm-6' %}
{% elseif multiple_len == 3 %}
{% set multiple_class = 'col-xs-12 col-sm-4' %}
{% elseif multiple_len == 4 %}
{% set multiple_class = 'col-xs-12 col-sm-3' %}
{% endif %}
{% endif %}

{% if multiple_class is not defined %}
{% set multiple_len = 3 %}
{% set multiple_class = 'col-xs-12 col-sm-4' %}
{% endif %}

{% set parent_id = item.id %}

{% include "@MaciPage/Media/_slider_indicators.html.twig" with { 'len': ((list|length / multiple_len)|number_format) } %}

<!-- Wrapper for slides -->
<div class="carousel-inner">

<div class="carousel-item image multiple active">

	<div class="row">

	{% for item in list %}

		<div class="multiple-item {{ multiple_class }}">

			<!-- Caption -->
			{% if caption == 'before' and caption and ( item.title or item.content ) %}
			<div class="carousel-caption d-none d-md-block">
				{% if item.title %}<h4>{{ item.title }}</h4>{% endif %}
				{% if item.content %}<div>{{ item.content|raw }}</div>{% endif %}
			</div>
			{% endif %}

			{% if item.link %}
			<a href="{{ item.link }}" alt="{{ item.title }}">
			{% endif %}

			<a href="{{ asset(path('maci_media_get', {'path': item.media.path})) }}" target="_blank"{% if item.media.type == 'image' %} data-toggle="lightbox" data-lightbox="media-slide-{{ parent_id }}" data-title="{{ item.title ? item.title : item.media.name }}" data-description="{{ item.content ? item.content : item.media.description }}" data-image="{{ asset(item.media.webPreview | imagine_filter('maci_media_lightbox')) }}"{% endif %}>
				<img class="img-fluid" src="{{ asset(item.webPreview | imagine_filter('maci_media_preview')) }}" {% if item.content %} title="{{ item.title }}" alt="{{ item.content }}" {% else %} alt="{{ item.title ? item.title : '#' }}" {% endif %} />
			</a>

			{% if item.link %}
			</a>
			{% endif %}

			<!-- Caption -->
			{% if caption == 'after' and caption and ( item.title or item.content ) %}
			<div class="carousel-caption d-none d-md-block">
				{% if item.title %}<h4>{{ item.title }}</h4>{% endif %}
				{% if item.content %}<div>{{ item.content|raw }}</div>{% endif %}
			</div>
			{% endif %}

		</div>

	{% if ( loop.index % multiple_len ) == 0 and not loop.last %}

	</div>
</div>
<div class="carousel-item image multiple">
	<div class="row">

	{% endif %}


	{% endfor %}

	</div>
</div>

</div>

{% include "@MaciPage/Media/_slider_controls.html.twig" %}

Resources/views/Media/_slider_quads_content.html.twig
{% if item.link %}
<a href="{{ item.link }}" alt="{{ item.title }}">
{% endif %}

{% if caption == 'before' and caption and ( item.title or item.content ) %}
<div class="carousel-caption">
	{% if item.title %}<h4>{{ item.title }}</h4>{% endif %}
	{% if item.content %}<div>{{ item.content|raw }}</div>{% endif %}
</div>
{% endif %}

<img class="d-block w-100" src="{{ asset(item.webPreview | imagine_filter(slider_filter)) }}" {% if item.content %} title="{{ item.title }}" alt="{{ item.content }}" {% else %} alt="{{ item.title ? item.title : '#' }}" {% endif %} />

{% if caption == 'after' and caption and ( item.title or item.content ) %}
<div class="carousel-caption">
	{% if item.title %}<h4>{{ item.title }}</h4>{% endif %}
	{% if item.content %}<div>{{ item.content|raw }}</div>{% endif %}
</div>
{% endif %}

{% if item.link %}
</a>
{% endif %}

Resources/views/Media/tag.html.twig
{% extends "@MaciPage/Layout/media.html.twig" %}


{% block maciadmin %}

{{ render(controller('MaciAdminBundle:View:adminBar', { 'entity': 'media_tag', 'item': tag } )) }}

{% endblock %}


{% block title %}

{{ tag.metaTitle }}

{% endblock %}

{% block description %}

<meta name="description" content="{{ tag.metaDescription }}" />

{% endblock %}


{% block pathBar %}
<nav>
<ol class="breadcrumb">

	{% if tag.type == 'brand' %}

    <li>
    	<a href="{{ path('maci_media_brands') }}">
    		{{ 'menu.media.brands' | matra('Brands') }}
    	</a>
    </li>

	{% else %}

    <li>
        <a href="{{ path('maci_media_tags') }}">
            {{ 'menu.media.tags' | matra('Media Tags') }}
        </a>
    </li>

	{% endif %}

    <li class="active">
    	{{ tag }}
    </li>

</ol>
</nav>
{% endblock %}


{% block content %}

{% include "@MaciPage/Media/_tag.html.twig" with { 'tag': tag } %}

{% endblock %}