Entity/Blog/Item.php
<?php

namespace Maci\PageBundle\Entity\Blog;

/**
 * Item
 */
class Item
{
	/**
	 * @var integer
	 */
	private $id;

	/**
	 * @var boolean
	 */
	private $favourite;

	/**
	 * @var integer
	 */
	private $position;

	/**
	 * @var \Maci\PageBundle\Entity\Blog\Post
	 */
	private $post;

	/**
	 * @var \Maci\PageBundle\Entity\Blog\Media
	 */
	private $media;


	/**
	 * Constructor
	 */
	public function __construct()
	{
		$this->favourite = false;
	}


	/**
	 * Get id
	 *
	 * @return integer 
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get favourite.
	 *
	 * @return bool
	 */
	public function getFavourite()
	{
		return $this->favourite;
	}

	/**
	 * Set favourite
	 *
	 * @param boolean $favourite
	 * @return Item
	 */
	public function setFavourite($favourite)
	{
		$this->favourite = $favourite;

		return $this;
	}

	/**
	 * Get favourite
	 *
	 * @return boolean 
	 */
	public function isFavourite()
	{
		return $this->favourite;
	}

	/**
	 * Set position
	 *
	 * @param integer $position
	 * @return Item
	 */
	public function setPosition($position)
	{
		$this->position = $position;

		return $this;
	}

	/**
	 * Get position
	 *
	 * @return integer 
	 */
	public function getPosition()
	{
		return $this->position;
	}

	/**
	 * Set post
	 *
	 * @param \Maci\PageBundle\Entity\Blog\Post $post
	 * @return Item
	 */
	public function setPost(\Maci\PageBundle\Entity\Blog\Post $post = null)
	{
		$this->post = $post;

		return $this;
	}

	/**
	 * Get post
	 *
	 * @return \Maci\PageBundle\Entity\Blog\Post 
	 */
	public function getPost()
	{
		return $this->post;
	}

	/**
	 * Set media
	 *
	 * @param \Maci\PageBundle\Entity\Media\Media $media
	 * @return Item
	 */
	public function setMedia(\Maci\PageBundle\Entity\Media\Media $media = null)
	{
		$this->media = $media;

		return $this;
	}

	/**
	 * Get media
	 *
	 * @return \Maci\PageBundle\Entity\Media\Media 
	 */
	public function getMedia()
	{
		return $this->media;
	}

	/**
	 * Get Name
	 */
	public function getName()
	{
		if (!$this->media)
			return null;

		return $this->getMedia()->getName();
	}

	/**
	 * Get Description
	 */
	public function getDescription()
	{
		if (!$this->media)
			return null;

		return $this->getMedia()->getDescription();
	}

	public function getWebPreview()
	{
		if (!$this->media)
			return '/images/defaults/document-icon.png';

		return $this->media->getWebPreview();
	}

	/**
	 * __toString()
	 */
	public function __toString()
	{
		return 'BlogMediaItem_' . (is_int($this->getId()) ? $this->getId() : 'New');
	}
}

Resources/views/BlogSlides/default.html.twig
<div id="blogSlide_{{ slide.id }}" class="post-slide">

{% if slide.preview %}
<figure id="blogSlidePreview_{{ slide.id }}" class="slide-preview post-preview-wrapper">
	<a class="post-preview-link d-block" href="{{ path('maci_media_get', {'path': slide.preview.path}) }}" data-lightbox="post-image" data-title="{{ slide.preview }}">
		<img class="post-preview img-fluid" src="{{ asset(slide.preview.webPath|imagine_filter('maci_blog_list')) }}" alt="{{ slide.preview.name }} - {{ slide.preview.description|striptags }}" />
	</a>
	{% if slide.preview.name or slide.preview.description %}
	<figcaption class="post-preview-caption">
		{% if slide.preview.name %}
		<span class="post-preview-name">{{ slide.preview.name }}</span>
		{% endif %}
		{% if slide.preview.name or slide.preview.description %}
		<div class="post-preview-description">{{ slide.preview.description|raw }}</div>
		{% endif %}
	</figcaption>
	{% endif %}
</figure>
{% endif %}

<div class="post-content slide-caption">

{% if slide.title %}
<h3 id="blogSlideTitle_{{ slide.id }}" class="slide-title pc-title">{{ slide.title }}</h3>
{% endif %}

{% if slide.content %}
<div id="blogSlideContent_{{ slide.id }}" class="slide-content">
{{ slide.content|raw }}
</div>
{% endif %}

</div>

</div>

Resources/views/BlogSlides/image.html.twig
<div id="blogSlide_{{ slide.id }}" class="post-slide">

{% if slide.preview %}
<figure id="blogSlidePreview_{{ slide.id }}" class="slide-preview post-preview-wrapper">
	<a class="post-preview-link d-block" href="{{ path('maci_media_get', {'path': slide.preview.path}) }}" data-lightbox="post-image" data-title="{{ slide.preview }}">
		<img class="post-preview img-fluid" src="{{ asset(slide.preview.webPath|imagine_filter('maci_blog_list')) }}" alt="{{ slide.preview.name }} - {{ slide.preview.description|striptags }}" />
	</a>
	<figcaption class="post-preview-caption">
		{% if slide.title %}
		<span class="post-preview-name">{{ slide.title }}</span>
		{% elseif slide.preview.name %}
		<span class="post-preview-name">{{ slide.preview.name }}</span>
		{% endif %}
		{% if slide.content %}
		<div class="post-preview-description">{{ slide.content|raw }}</div>
		{% elseif slide.preview.description %}
		<div class="post-preview-description">{{ slide.preview.description|raw }}</div>
		{% endif %}
		{% if post.preview.credits %}
		<div class="post-preview-credits">
			<span class="post-preview-credits-label">{{ 'media.credits'|matra('Credits') }}:</span>
			<a class="post-preview-credits" href="{{ post.preview.creditsLink }}" rel="nofollow" target="_blank">{{ post.preview.creditsTitle }}</a>
		</div>
		{% endif %}
	</figcaption>
</figure>
{% endif %}

</div>