Entity/Blog/Author.php
<?php

namespace Maci\PageBundle\Entity\Blog;

/**
 * Author
 */
class Author
{
	/**
	 * @var integer
	 */
	private $id;

	/**
	 * @var string
	 */
	private $name;

	/**
	 * @var string
	 */
	private $description;

	/**
	 * @var string
	 */
	private $path;

	/**
	 * @var string
	 */
	private $locale;

	/**
	 * @var \Maci\UserBundle\Entity\User
	 */
	private $user;

	/**
	 * @var \Maci\PageBundle\Entity\Media\Media
	 */
	private $preview;

	/**
	 * @var \Doctrine\Common\Collections\Collection
	 */
	private $editors;

	/**
	 * Constructor
	 */
	public function __construct()
	{
		$this->path = uniqid();
		$this->editors = new \Doctrine\Common\Collections\ArrayCollection();
	}

	/**
	 * Get id
	 *
	 * @return integer 
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Set name
	 *
	 * @param string $name
	 * @return Author
	 */
	public function setName($name)
	{
		$this->name = $name;

		return $this;
	}

	/**
	 * Get name
	 *
	 * @return string 
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Set description
	 *
	 * @param string $description
	 * @return Author
	 */
	public function setDescription($description)
	{
		$this->description = $description;

		return $this;
	}

	/**
	 * Get description
	 *
	 * @return string 
	 */
	public function getDescription()
	{
		return $this->description;
	}

	/**
	 * Set path
	 *
	 * @param string $path
	 * @return Author
	 */
	public function setPath($path)
	{
		$this->path = $path;

		return $this;
	}

	/**
	 * Get path
	 *
	 * @return string 
	 */
	public function getPath()
	{
		return $this->path;
	}

	public function setLocale($locale)
	{
		$this->locale = $locale;

		return $this;
	}

	public function getLocale()
	{
		return $this->locale;
	}

	/**
	 * Set user
	 *
	 * @param \Maci\UserBundle\Entity\User $user
	 * @return Post
	 */
	public function setUser(\Maci\UserBundle\Entity\User $user = null)
	{
		$this->user = $user;

		return $this;
	}

	/**
	 * Get user
	 *
	 * @return \Maci\UserBundle\Entity\User 
	 */
	public function getUser()
	{
		return $this->user;
	}

	/**
	 * Set preview
	 *
	 * @param \Maci\PageBundle\Entity\Media\Media $preview
	 * @return Author
	 */
	public function setPreview(\Maci\PageBundle\Entity\Media\Media $preview = null)
	{
		$this->preview = $preview;

		return $this;
	}

	/**
	 * Get preview
	 *
	 * @return \Maci\PageBundle\Entity\Media\Media 
	 */
	public function getPreview()
	{
		return $this->preview;
	}

	public function getWebPreview()
	{
		if (!$this->preview) {
			return '/images/defaults/document-icon.png';
		}
		return $this->preview->getWebPath();
	}

	/**
	 * Add editors
	 *
	 * @param \Maci\PageBundle\Entity\Blog\Editor $editors
	 * @return Author
	 */
	public function addEditor(\Maci\PageBundle\Entity\Blog\Editor $editors)
	{
		$this->editors[] = $editors;

		return $this;
	}

	/**
	 * Remove editors
	 *
	 * @param \Maci\PageBundle\Entity\Blog\Editor $editors
	 */
	public function removeEditor(\Maci\PageBundle\Entity\Blog\Editor $editors)
	{
		$this->editors->removeElement($editors);
	}

	/**
	 * Get editors
	 *
	 * @return \Doctrine\Common\Collections\Collection 
	 */
	public function getEditors()
	{
		return $this->editors;
	}

	/**
	 * __toString()
	 */
	public function __toString()
	{
		return 'BlogAuthor#' . ($this->id ? $this->id : 'New');
	}
}

Entity/Blog/Post.php
<?php

namespace Maci\PageBundle\Entity\Blog;

/**
 * Post
 */
class Post
{
	/**
	 * @var integer
	 */
	private $id;

	/**
	 * @var string
	 */
	private $title;

	/**
	 * @var string
	 */
	private $subtitle;

	/**
	 * @var string
	 */
	private $content;

	/**
	 * @var string
	 */
	private $markdown;

	/**
	 * @var string
	 */
	private $preheader;

	/**
	 * @var string
	 */
	private $header;

	/**
	 * @var integer
	 */
	private $status;

	/**
	 * @var string
	 */
	private $path;

	/**
	 * @var string
	 */
	private $link;

	/**
	 * @var string
	 */
	private $permalink;

	/**
	 * @var string
	 */
	private $meta_title;

	/**
	 * @var text
	 */
	private $meta_description;

	/**
	 * @var \DateTime
	 */
	private $created;

	/**
	 * @var \DateTime
	 */
	private $updated;

	/**
	 * @var \DateTime
	 */
	private $pubblished;

	/**
	 * @var boolean
	 */
	private $removed;

	/**
	 * @var \Doctrine\Common\Collections\Collection
	 */
	private $comments;

	/**
	 * @var \Doctrine\Common\Collections\Collection
	 */
	private $editors;

	/**
	 * @var \Doctrine\Common\Collections\Collection
	 */
	private $tags;

	/**
	 * @var \Doctrine\Common\Collections\Collection
	 */
	private $items;

	/**
	 * @var \Doctrine\Common\Collections\Collection
	 */
	private $slides;

	/**
	 * @var \Maci\PageBundle\Entity\Media\Media
	 */
	private $preview;

	/**
	 * @var \Doctrine\Common\Collections\Collection
	 */
	private $sources;

	/**
	 * @var \Doctrine\Common\Collections\Collection
	 */
	private $targets;

	/**
	 * @var string
	 */
	private $locale;

	/**
	 * Constructor
	 */
	public function __construct()
	{
		$this->comments = new \Doctrine\Common\Collections\ArrayCollection();
		$this->tags = new \Doctrine\Common\Collections\ArrayCollection();
		$this->items = new \Doctrine\Common\Collections\ArrayCollection();
		$this->slides = new \Doctrine\Common\Collections\ArrayCollection();
		$this->sources = new \Doctrine\Common\Collections\ArrayCollection();
		$this->targets = new \Doctrine\Common\Collections\ArrayCollection();
		$this->removed = false;
		$this->status = 'new';
        $this->path = uniqid();
		$this->link = $this->path;
	}

	/**
	 * Get id
	 *
	 * @return integer 
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Set title
	 *
	 * @param string $title
	 * @return PostTranslation
	 */
	public function setTitle($title)
	{
		$this->title = $title;

		return $this;
	}

	/**
	 * Get title
	 *
	 * @return string 
	 */
	public function getTitle()
	{
		return $this->title;
	}

	public function setSubtitle($subtitle)
	{
		$this->subtitle = $subtitle;

		return $this;
	}

	public function getSubtitle()
	{
		return $this->subtitle;
	}

	/**
	 * Set content
	 *
	 * @param string $content
	 * @return PostTranslation
	 */
	public function setContent($content)
	{
		$this->content = $content;

		return $this;
	}

	/**
	 * Get content
	 *
	 * @return string 
	 */
	public function getContent()
	{
		return $this->content;
	}

	/**
	 * Set markdown
	 *
	 * @param string $markdown
	 * @return PostTranslation
	 */
	public function setMarkdown($markdown)
	{
		$this->markdown = $markdown;

		return $this;
	}

	/**
	 * Get markdown
	 *
	 * @return string 
	 */
	public function getMarkdown()
	{
		return $this->markdown;
	}

	/**
	 * Set preheader
	 *
	 * @param string $preheader
	 * @return PostTranslation
	 */
	public function setPreheader($preheader)
	{
		$this->preheader = $preheader;

		return $this;
	}

	/**
	 * Get preheader
	 *
	 * @return string 
	 */
	public function getPreheader()
	{
		return $this->preheader;
	}

	/**
	 * Set header
	 *
	 * @param string $header
	 * @return PostTranslation
	 */
	public function setHeader($header)
	{
		$this->header = $header;

		return $this;
	}

	/**
	 * Get header
	 *
	 * @return string 
	 */
	public function getHeader()
	{
		return $this->header;
	}

	/**
	 * Set status
	 *
	 * @param integer $status
	 * @return Post
	 */
	public function setStatus($status)
	{
		$this->status = $status;

		return $this;
	}

	/**
	 * Get status
	 *
	 * @return integer 
	 */
	public function getStatus()
	{
		return $this->status;
	}

	/**
	 * Get Status Array
	 */
	public function getStatusArray()
	{
		return [
			'New' => 'new',
			'Draft' => 'draft',
			// 'Scheduled' => 'scheduled',
			'Pubblished' => 'pubblished',
			'Updated' => 'updated'
		];
	}

	public function getStatusLabel()
	{
		return \Maci\PageBundle\MaciPageBundle::getLabel($this->status, $this->getStatusArray());
	}

	static public function getStatusValues()
	{
		return array_values(Post::getStatusArray());
	}

	public function isPubblished()
	{
		return !!$this->pubblished && ($this->status == 'pubblished' || $this->status == 'updated');
	}

	public function isUpdated()
	{
		return !!$this->pubblished && ($this->status == 'updated');
	}

	/**
	 * Set path
	 *
	 * @param string $path
	 * @return Post
	 */
	public function setPath($path)
	{
		$this->path = $path;

		return $this;
	}

	/**
	 * Get path
	 *
	 * @return string 
	 */
	public function getPath()
	{
		return $this->path;
	}

	/**
	 * Set link
	 *
	 * @param string $link
	 * @return Post
	 */
	public function setLink($link)
	{
		$this->link = $link;

		return $this;
	}

	/**
	 * Get link
	 *
	 * @return string 
	 */
	public function getLink()
	{
		return $this->link;
	}

	/**
	 * Set permalink
	 *
	 * @param string $permalink
	 * @return Post
	 */
	public function setPermalink($permalink)
	{
		$this->permalink = $permalink;

		return $this;
	}

	/**
	 * Get permalink
	 *
	 * @return string 
	 */
	public function getPermalink()
	{
		return $this->permalink;
	}

	/**
	 * Set title
	 */
	public function setMetaTitle($meta_title)
	{
		$this->meta_title = $meta_title;

		return $this;
	}

	/**
	 * Get title
	 */
	public function getMetaTitle()
	{
		return $this->meta_title;
	}

	/**
	 * Set description
	 */
	public function setMetaDescription($meta_description)
	{
		$this->meta_description = $meta_description;

		return $this;
	}

	/**
	 * Get description
	 */
	public function getMetaDescription()
	{
		return $this->meta_description;
	}

	/**
	 * Set created
	 *
	 * @param \DateTime $created
	 * @return Post
	 */
	public function setCreated($created)
	{
		$this->created = $created;

		return $this;
	}

	/**
	 * Get created
	 *
	 * @return \DateTime 
	 */
	public function getCreated()
	{
		return $this->created;
	}

	/**
	 * Set updated
	 *
	 * @param \DateTime $updated
	 * @return Post
	 */
	public function setUpdated($updated)
	{
		$this->updated = $updated;

		return $this;
	}

	/**
	 * Get updated
	 *
	 * @return \DateTime 
	 */
	public function getUpdated()
	{
		return $this->updated;
	}

	/**
	 * Set pubblished
	 *
	 * @param \DateTime $pubblished
	 * @return Post
	 */
	public function setPubblished($pubblished)
	{
		$this->pubblished = $pubblished;

		return $this;
	}

	/**
	 * Get pubblished
	 *
	 * @return \DateTime 
	 */
	public function getPubblished()
	{
		return $this->pubblished;
	}

	public function setRemoved($removed)
	{
		$this->removed = $removed;

		return $this;
	}

	public function getRemoved()
	{
		return $this->removed;
	}

	/**
	 * Add comments
	 *
	 * @param \Maci\PageBundle\Entity\Blog\Comment $comments
	 * @return Post
	 */
	public function addComment(\Maci\PageBundle\Entity\Blog\Comment $comments)
	{
		$this->comments[] = $comments;

		return $this;
	}

	/**
	 * Remove comments
	 *
	 * @param \Maci\PageBundle\Entity\Blog\Comment $comments
	 */
	public function removeComment(\Maci\PageBundle\Entity\Blog\Comment $comments)
	{
		$this->comments->removeElement($comments);
	}

	/**
	 * Get comments
	 *
	 * @return \Doctrine\Common\Collections\Collection 
	 */
	public function getComments()
	{
		return $this->comments;
	}

	/**
	 * Get approved children
	 *
	 * @return \Doctrine\Common\Collections\Collection 
	 */
	public function getApprovedComments()
	{
		return $this->comments->filter(function($e){
			return $e->getApproved();
		});
	}

	/**
	 * Add editors
	 *
	 * @param \Maci\PageBundle\Entity\Blog\Editor $editors
	 * @return Post
	 */
	public function addEditor(\Maci\PageBundle\Entity\Blog\Editor $editors)
	{
		$this->editors[] = $editors;

		return $this;
	}

	/**
	 * Remove editors
	 *
	 * @param \Maci\PageBundle\Entity\Blog\Editor $editors
	 */
	public function removeEditor(\Maci\PageBundle\Entity\Blog\Editor $editors)
	{
		$this->editors->removeElement($editors);
	}

	/**
	 * Get editors
	 *
	 * @return \Doctrine\Common\Collections\Collection 
	 */
	public function getEditors()
	{
		return $this->editors;
	}

	public function getAuthors()
	{
		return $this->getEditors()->filter(function($e){
			return $e->isAuthor();
		});
	}

	public function getTranslators()
	{
		return $this->getEditors()->filter(function($e){
			return $e->isTranslator();
		});
	}

	public function getAuthor()
	{
		$list = $this->getAuthors();

		return count($list) == 0 ? null : $list[0];
	}

	/**
	 * Add tags
	 *
	 * @param \Maci\PageBundle\Entity\Blog\Tag $tags
	 * @return Post
	 */
	public function addTag(\Maci\PageBundle\Entity\Blog\Tag $tags)
	{
		$this->tags[] = $tags;

		return $this;
	}

	/**
	 * Remove tags
	 *
	 * @param \Maci\PageBundle\Entity\Blog\Tag $tags
	 */
	public function removeTag(\Maci\PageBundle\Entity\Blog\Tag $tags)
	{
		$this->tags->removeElement($tags);
	}

	/**
	 * Get tags
	 *
	 * @return \Doctrine\Common\Collections\Collection 
	 */
	public function getTags()
	{
		return $this->tags;
	}

	/**
	 * Add Source.
	 *
	 * @param \Maci\PageBundle\Entity\Blog\Related $source
	 *
	 * @return Post
	 */
	public function addSource(\Maci\PageBundle\Entity\Blog\Related $source)
	{
		$this->sources[] = $source;

		return $this;
	}

	/**
	 * Remove Source.
	 *
	 * @param \Maci\PageBundle\Entity\Blog\Related $source
	 *
	 * @return boolean TRUE if this collection contained the specified element, FALSE otherwise.
	 */
	public function removeSource(\Maci\PageBundle\Entity\Blog\Related $source)
	{
		return $this->sources->removeElement($source);
	}

	/**
	 * Get Sources.
	 *

Form/Blog/BlogPostType.php
<?php

namespace Maci\PageBundle\Form\Blog;

use Maci\PageBundle\Entity\Blog\Post;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

use Symfony\Component\Form\Extension\Core\Type\ResetType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;


/**
 * Post
 */
class BlogPostType extends AbstractType
{
	public function setDefaultOptions(OptionsResolverInterface $resolver)
	{
		$resolver->setDefaults(array(
			'data_class' => Post::class,
			// 'cascade_validation' => true,
		));
	}

	public function buildForm(FormBuilderInterface $builder, array $options)
	{
		$builder
			->add('title')
			->add('subtitle', null, array('required' => false))
			->add('header', null, array('required' => false))
			->add('content', null, array('required' => false))
			->add('meta_title', null, array('required' => false))
			->add('meta_description', null, array('required' => false))
			->add('locale')
			->add('reset', ResetType::class)
			->add('save', SubmitType::class)
		;
	}

	public function getName()
	{
		return 'blog_post';
	}
}

Form/Blog/CommentType.php
<?php

namespace Maci\PageBundle\Form\Blog;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;

use EWZ\Bundle\RecaptchaBundle\Form\Type\EWZRecaptchaType;
use EWZ\Bundle\RecaptchaBundle\Validator\Constraints\IsTrue as RecaptchaTrue;

/**
 * CommentType
 */
class CommentType extends AbstractType
{
	protected $authorizationChecker;

	public function __construct(AuthorizationCheckerInterface $authorizationChecker)
	{
		$this->authorizationChecker = $authorizationChecker;
	}

	public function configureOptions(OptionsResolver $resolver)
	{
		$resolver->setDefaults([
			'data_class' => 'Maci\PageBundle\Entity\Blog\Comment',
			'env' => 'prod'
		]);
	}

	public function buildForm(FormBuilderInterface $builder, array $options)
	{
		if ($this->authorizationChecker->isGranted('ROLE_USER'))
		{
			$builder->add('content');
		}
		else
		{
			$builder
				->add('name')
				->add('email')
				->add('content')
				->add('notify', CheckboxType::class, [
					'required' => false
				])
				->add('newsletter', CheckboxType::class, [
					'mapped' => false,
					'required' => false
				])
			;
			if($options['env'] === "prod")
				$builder->add('recaptcha', EWZRecaptchaType::class, [
					'label_attr'  => ['class'=> 'sr-only'],
					'mapped'      => false,
					'constraints' => [new RecaptchaTrue()]
				]);
		}

		$builder->add('_parent', HiddenType::class, [
			'mapped' => false
		]);
		$builder->add('send_comment', SubmitType::class);
	}

	public function getName()
	{
		return 'blog_comment';
	}
}

Form/Blog/MediaItemType.php
<?php

namespace Maci\PageBundle\Form\Blog;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

/**
 * MediaItem
 */
class MediaItemType extends AbstractType
{
	public function setDefaultOptions(OptionsResolverInterface $resolver)
	{
		$resolver->setDefaults(array(
			'data_class' => 'Maci\PageBundle\Entity\Media\MediaItem',
			// 'cascade_validation' => true,
		));
	}

	public function buildForm(FormBuilderInterface $builder, array $options)
	{
		$builder
			->add('favourite', 'choice', array(
				'choices'   => array(0 => 'No', 1 => 'Yes')
			))
			->add('reset', 'reset')
			->add('send', 'submit')
		;
	}

	public function getName()
	{
		return 'blog_tag_item';
	}
}

Resources/views/Blog/_article.html.twig
<article class="blog-post post-article clearfix">
<div class="blog-post-wrapper flex">

<header class="blog-post-header">

	<h1 class="post-title">{{ post.title }}</h1>

	{% if post.subtitle %}
	<h2 class="post-subtitle">{{ post.subtitle }}</h2>
	{% endif %}

</header>

<section class="blog-post-info flex">

	{% include "@MaciPage/Blog/_post_collapsed_nav.html.twig" %}

</section>

<figure class="post-preview-wrapper">
	{% if post.preview %}
	<a class="post-preview-link d-block" href="{{ path('maci_media_get', {'path': post.preview.path}) }}" data-lightbox="post-image" data-title="{{ post.preview }}">
		<img class="post-preview img-fluid" src="{{ asset(post.preview.webPath|imagine_filter('maci_blog_list')) }}" alt="{{ post.preview }} - {{ post.preview.description|striptags }}" />
	</a>
	{% if post.preview.name or post.preview.description or slide.preview.credits %}
	<figcaption class="post-preview-caption">
		{% if post.preview.name %}
		<span class="post-preview-name">{{ post.preview.name }}</span>
		{% endif %}
		{% if post.preview.description %}
		<div class="post-preview-description">{{ post.preview.description|raw }}</div>
		{% endif %}
		{% if post.preview.credits %}
		<div class="post-preview-credits">
			<span class="post-preview-credits-label">{{ 'media.credits'|matra('Credits') }}:</span>
			<a class="post-preview-credits" href="{{ post.preview.creditsLink }}" rel="nofollow" target="_blank">{{ post.preview.creditsTitle }}</a>
		</div>
		{% endif %}
	</figcaption>
	{% endif %}
	{% else %}
	<img class="post-preview default img-fluid" src="{{ asset('/images/defaults/media-icon.png') }}" alt="{{ post.title }}" />
	{% endif %}
</figure>

{% if post.previousPosts|length %}
<section class="related-list related-prev">
	<h3 class="list-title related">
		{% if post.previousPosts|length == 1 %}
		{{ 'blog.post.related.prev-post'|matra('Previous Post') }}:
		{% else %}
		{{ 'blog.post.related.prev-posts'|matra('Previous Posts') }}:
		{% endif %}
	</h3>
	{% include "@MaciPage/Blog/_related_posts.html.twig" with {'list': post.previousPosts } %}
</section>
{% endif %}

<section class="blog-post-content">
	{% if post.preheader is not null %}
	<div class="post-content post-preheader">{{ post.preheader|raw }}</div>
	{% endif %}
	{% if post.header is not null %}
	<div class="post-content post-header">{{ post.header|raw }}</div>
	{% endif %}
	{% if post.markdown is not null %}
	<div class="post-content markdown-content">{{ post.markdown|markdown|nl2br }}</div>
	{% endif %}
	{% if post.content is not null %}
	<div class="post-content item-content">{{ post.content|raw }}</div>
	{% endif %}
</section>

{% if post.slides %}
<section class="blog-post-slides">
	{% for slide in post.slides %}
	{% include "@MaciPage/Blog/_slide.html.twig" %}
	{% endfor %}
</section>
{% endif %}

{% if post.images|length %}
<section class="blog-post images">
	{% include "@MaciPage/Blog/_media_list.html.twig" with {'list': post.images} %}
</section>
{% endif %}

{% if post.otherMedias|length %}
<section class="related-list downloads">
	<h3 class="list-title related">
		{{ 'blog.post.download'|matra('Download') }}:
	</h3>
	{% include "@MaciPage/Blog/_downloads.html.twig" with {'list': post.otherMedias} %}
</section>
{% endif %}

{% if post.nextPosts|length %}
<section class="related-list related-next">
	<h3 class="list-title related">
		{% if post.nextPosts|length == 1 %}
		{{ 'blog.post.related.next-post'|matra('Next Post') }}:
		{% else %}
		{{ 'blog.post.related.next-posts'|matra('Next Posts') }}:
		{% endif %}
	</h3>
	{% include "@MaciPage/Blog/_related_posts.html.twig" with {'list': post.nextPosts } %}
</section>
{% endif %}

<footer class="blog-post-footer flex">
	{% include "@MaciPage/Blog/_post_author_nav.html.twig" %}
	{% include "@MaciPage/Blog/_post_dates_nav.html.twig" %}
	{% include "@MaciPage/Blog/_post_tags_nav.html.twig" %}
	{% include "@MaciPage/Blog/_post_links_nav.html.twig" %}
	{% if is_granted('ROLE_ADMIN') %}
	{{ render(controller('MaciAdminBundle:View:adminBar', { 'entity': 'blog_post', 'item': post } )) }}
	{% endif %}
</footer>

{% include "@MaciPage/Blog/_license.html.twig" %}

{% if post.editors|length %}
<section class="related-list editors">
	<h3 class="list-title related">
		{% if post.editors|length == 1 %}
		{{ 'blog.author'|matra('Author') }}:
		{% else %}
		{{ 'blog.authors'|matra('Authors') }}:
		{% endif %}
	</h3>
	{% include "@MaciPage/Blog/_editors.html.twig" with { 'list': post.editors } %}
</section>
{% endif %}

{% if post.related|length %}
<section class="related-list related-posts">
	<h3 class="list-title related">
		{% if post.related|length == 1 %}
		{{ 'blog.post.related-post'|matra('Related Post') }}:
		{% else %}
		{{ 'blog.post.related-posts'|matra('Related Posts') }}:
		{% endif %}
	</h3>
	{% include "@MaciPage/Blog/_related_posts.html.twig" with {'list': post.related } %}
</section>
{% endif %}

<section class="related-list comments">
	<h3 class="list-title related">
		{{ 'blog.post.comments'|matra('Comments') }}
	</h3>
	{% if is_granted('ROLE_ADMIN') and post.comments|length %}
	{% include "@MaciPage/Blog/_comments_list.html.twig" with {'list': post.comments} %}
	{% elseif post.approvedComments|length %}
	{% include "@MaciPage/Blog/_comments_list.html.twig" with {'list': post.approvedComments} %}
	{% else %}
	<h4 class="pc-title no-comments">
		{{ 'blog.post.no-comments'|matra('No comments here.') }}
	</h4>
	{% endif %}
	<div class="addCommentWrapper">
		<h4 class="pc-title add-comment">
			{{ 'blog.post.add-comment'|matra('Add a comment') }}:
		</h4>
		{% include "@MaciPage/Blog/_comment_form.html.twig" with {'form': commentForm} %}
	</div>
</section>

</div>
</article>

Resources/views/Blog/_post_author_nav.html.twig
<nav class="post-author-nav navbar navbar-expand flex-column">
	<ul class="navbar-nav mr-auto">

		{% if post.editors|length %}

		{% if post.authors|length %}
		<li class="nav-item">
			<p class="navbar-text">
				{% if post.authors|length == 1 %}
				<span class="post-author post-nav-label">{{ 'blog.author'|matra('Author') }}:</span>
				<a class="post-author post-nav-val" href="{{ path('maci_blog_author', { 'path': post.author.path, '_locale': post.author.locale }) }}">{{ post.author.name }}</a>
				{% else %}
				<span class="post-author post-nav-label">{{ 'blog.authors'|matra('Authors') }}:</span>
				{% for author in post.authors %}
				<a class="post-author post-nav-val" href="{{ path('maci_blog_author', { 'path': author.path, '_locale': author.locale }) }}">{{ author.name }}</a>{{ loop.last ? '' : ', ' }}
				{% endfor %}
				{% endif %}
			</p>
		</li>
		{% endif %}

		{% if post.translators|length %}
		<li class="nav-item">
			<p class="navbar-text">
				{% if post.translators|length == 1 %}
				<span class="post-author translator post-nav-label">{{ 'blog.translator'|matra('Translator') }}:</span>
				<a class="post-author translator post-nav-val" href="{{ path('maci_blog_author', { 'path': post.translator.path, '_locale': post.translator.locale }) }}">{{ post.translator.name }}</a>
				{% else %}
				<span class="post-author translator post-nav-label">{{ 'blog.translators'|matra('Translators') }}:</span>
				{% for translator in post.translators %}
				<a class="post-author translator post-nav-val" href="{{ path('maci_blog_author', { 'path': translator.path, '_locale': translator.locale }) }}">{{ translator.name }}</a>{{ loop.last ? '' : ', ' }}
				{% endfor %}
				{% endif %}
			</p>
		</li>
		{% endif %}

		{% else %}

		<li class="nav-item">
			<p class="navbar-text">
				<span class="post-author post-nav-label">{{ 'blog.author'|matra('Author') }}:</span>
				<span class="post-author post-nav-val">{{ company_title }}</span>
			</p>
		</li>

		{% endif %}

	</ul>
</nav>